---

- name: Clone local features
  git: 
    clone: yes
    repo: "https://github.com/lsulibraries/islandora-features.git"
    dest: "{{ drupal_core_path }}/sites/all/modules/islandora-features"
    update: yes

- name: Enable features
  command: 'drush -y  en {{ item[1] }}'
  args:
    chdir: "{{ drupal_core_path }}/sites/{{ item[0] }}"
  with_nested:
    - "{{ institutions }}"
    - "{{ local_features }}"

- name: revert block setting
  command: 'drush fr -y' 
  args:
    chdir: "{{ drupal_core_path }}/sites/{{ item }}"
  with_items: "{{ institutions }}"