---
- name: Cloning local modules
  git: clone=yes repo="https://github.com/lsulibraries/{{item}}.git" dest="{{modules_dir}}/{{item}}" update=yes
  with_items: "{{ local_mods }}"

- name: enable local modules
  shell: "drush -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ local_mods }}"