---
- name: set front page
  command: 'drush vset site_frontpage islandora-collection-landing-pages'
  args:
    chdir: "{{ drupal_core_path }}"
    
- name: set theme
  command: 'drush vset theme_default subtheme_lsu'
  args:
    chdir: "{{ drupal_core_path }}"
    
- name: set site name
  command: 'drush vset site_name {{ drupal_site_name  }}'
  args:
    chdir: "{{ drupal_core_path }}"


#- name: revert block setting
#  command: 'drush features-revert blocks_lsu'
# this command features-revert (which works fine in cli once provisioned) doesn't work here. drush can't find features-revert command

