---
- name: Cloning local modules
  git: clone=yes repo="https://github.com/lsulibraries/islandora-features.git" dest="{{modules_dir}}/islandora-features" update=yes

- name: enable local modules
  shell: "drush -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ local_mods }}"
