---
- include: system.yml
- include: modules.yml
- include: variables.yml
- include: roles-permissions.yml
- include: content.yml

- name: 'Restart tomcat ## 2017012517 # 2016112310'
  service:
    name: tomcat7
    state: restarted

- name: feature revert
  command: drush fra -y
  args:
    chdir: '{{ drupal_core_path }}'

- name: clear cache
  command: drush cc all
  args:
    chdir: '{{ drupal_core_path }}'

- name: set permissions.
  shell: "sh /opt/scripts/drupal-permissions/drupal-fix-permissions.sh --drupal_path={{ drupal_core_path }} --drupal_user=root --httpd_group=www-data"
  when: environment_type != 'dev'
