---
 include: local_mods.yml
- include: cdmMigrate.yml
- include: local_vars.yml

- name: reset permissions in modules dir
  file:
    state: directory
    path: "{{ drupal_core_path }}/sites/all/modules"
    owner: www-data
    group: www-data
    recurse: true

- name: reset permissions in themes dir
  file:
    state: directory
    path: "{{ drupal_core_path }}/sites/all/themes"
    owner: www-data
    group: www-data
    recurse: true


- name: Cloning local features
  git: clone=yes  repo="https://github.com/lsulibraries/islandora-features.git" dest="{{modules_dir}}/islandora-features" update=yes
