---
- include: local_subtheme.yml
- include: local_mods.yml
- include: cdmMigrate.yml

- name: reset permissions in modules dir
  file:
    state: directory
    path: "{{ drupal_core_path }}/sites/all/modules"
    owner: www-data
    group: www-data
    recurse: true

- name: reset permissions in themes dir
  file:
    state: directory
    path: "{{ drupal_core_path }}/sites/all/themes"
    owner: www-data
    group: www-data
    recurse: true

- name: Cloning local modules
  git: clone=yes repo="https://github.com/lsulibraries/{{item}}.git" dest="{{modules_dir}}/{{item}}" update=yes
  with_items: "{{ local_mods }}"

- name: enable local modules
  shell: "drush -y en {{ item }}"
  args:
    chdir: "{{ drupal_core_path }}"
  with_items: "{{ local_mods }}"

- name: Clone mjordan migration tool
  git:
    clone: yes
    repo: https://github.com/mjordan/islandora_cdm_api.git
    dest: "{{ modules_dir }}/islandora_cdm_api"