---
- include: local_mods.yml
- include: cdmMigrate.yml
- include: local_vars.yml

- name: reset permissions in modules dir
  file:
    state: directory
    path: "{{ drupal_core_path }}/sites/all/modules"
    owner: www-data
    group: www-data
    recurse: true

