---
- name: set simple vars
  command: 'drush vset {{ item[1].name }} {{ item[1].value }}'
  args:
    chdir: "{{ drupal_core_path }}/sites/{{ item[0] }}"
  with_nested: 
    - "{{ institutions }}"
    - "{{ simple_vars }}"

#- name: set theme
#  command: 'drush vset theme_default subtheme_lsu'
#  args:
#    chdir: "{{ drupal_core_path }}/sites/{{ item }}"  
#  with_items: "{{ institutions }}"

- name: set site name
  command: 'drush vset site_name {{ item.name  }}'
  args:
    chdir: "{{ drupal_core_path }}/sites/{{ item.inst }}"
  with_items: "{{ site_names }}"
